#!/usr/bin/env bash

########
#
# This is a simple mirroring script for Arch Linux 32. 
# To save bandwidth it first checks a timestamp via rsync and only runs 
# full rsync when the timestamp differs from the local copy.
#
########

# Directory where the repo is stored locally.
target="/data/mirror/archlinux32/"

# If you want to limit the bandwidth used by rsync set this.
# Use 0 to disable the limit.
# The default unit is KiB (see man rsync /--bwlimit for more)
bwlimit=0

# The source URL of the mirror you want to sync from.
source_url='rsync://buildmaster.archlinux32.org/archlinux32/'

#### END CONFIG

[ ! -d "${target}" ] && mkdir -p "${target}"

rsync_cmd() {
  local -a cmd=(rsync -rlptH --safe-links --delete-delay --delay-updates
    "--timeout=600" "--contimeout=60" --no-motd)

  if stty &>/dev/null; then
    cmd+=(-h -v --progress)
  else
    cmd+=(--quiet)
  fi

  if ((bwlimit>0)); then
    cmd+=("--bwlimit=$bwlimit")
  fi

  "${cmd[@]}" "$@"
}


# If we are called without a tty (cronjob/systemd timer) only run when there are changes.
# We fetch only the 'lastupdate' file to a temporary location using rsync
# and compare it against the local copy.
if ! tty -s && [[ -f "$target/lastupdate" ]]; then
  # Create a secure temporary file
  tmp_lastupdate=$(mktemp)
  
  # Fetch exclusively the 'lastupdate' file from the server via rsync
  rsync -q "${source_url%/}/lastupdate" "$tmp_lastupdate"
  
  # Compare the files
  if diff -b "$tmp_lastupdate" "$target/lastupdate" >/dev/null; then
    rm -f "$tmp_lastupdate"
    
    # Keep lastsync file in sync for statistics generated by the Arch Linux website
    rsync_cmd "${source_url%/}/lastsync" "$target/lastsync"
    exit 0
  fi
  
  # Cleanup temp file if there are changes and we need to do a full run
  rm -f "$tmp_lastupdate"
fi

rsync_cmd \
  "${source_url}" \
  "${target}"
