name: "CI"
on:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: ufscar
          authToken: '${{ secrets.CACHIX_KEY }}'
      - run: |
          nix build ".#nixosConfigurations.mirror.config.system.build.toplevel"
