name: "Update flake inputs"

on:
  schedule:
    - cron: '45 11 * * *'

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: ufscar
          authToken: ${{ secrets.CACHIX_KEY }}

      - name: Update flake inputs
        run: |
          nix flake update
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "chore: update flake inputs" flake.lock && git push || echo "Nothing to commit"
